apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubecost
  namespace: kubecost
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/kubecost-irsa
---
AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role for Kubecost IRSA
Resources:
  KubecostRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: kubecost-irsa
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: arn:aws:iam::111122223333:oidc-provider/oidc.eks.ap-northeast-2.amazonaws.com/id/EXAMPLED539D4633E53DE1B716D3041E
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                oidc.eks.ap-northeast-2.amazonaws.com/id/EXAMPLED539D4633E53DE1B716D3041E:sub: "system:serviceaccount:kubecost:kubecost"
      Policies:
        - PolicyName: kubecost
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ce:GetCostAndUsage
                Resource: "*"
